# Generated by Django 2.0.3 on 2018-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.CharField(default='null', max_length=255, primary_key=True, serialize=False)),
                ('ethaddress', models.CharField(default='null', max_length=255)),
                ('indicativecontribution', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actualcontribution', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mytoken', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonustoken', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tokenwithdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
