# Generated by Django 2.0.3 on 2018-03-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180315_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=254, primary_key=True, serialize=False),
        ),
    ]
